controller_list:
  - name: fake_manipulator_controller
    joints:
      - /ur10_1/shoulder_pan_joint
      - /ur10_1/shoulder_lift_joint
      - /ur10_1/elbow_joint
      - /ur10_1/wrist_1_joint
      - /ur10_1/wrist_2_joint
      - /ur10_1/wrist_3_joint
  - name: fake_gripper_controller
    joints:
      - /ur10_1/robotiq_85_left_knuckle_joint