# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: manipulator
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - /ur10_1/shoulder_pan_joint
    - /ur10_1/shoulder_lift_joint
    - /ur10_1/elbow_joint
    - /ur10_1/wrist_1_joint
    - /ur10_1/wrist_2_joint
    - /ur10_1/wrist_3_joint
    - /ur10_1/robotiq_85_left_knuckle_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: manipulator_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - /ur10_1/shoulder_pan_joint
      - /ur10_1/shoulder_lift_joint
      - /ur10_1/elbow_joint
      - /ur10_1/wrist_1_joint
      - /ur10_1/wrist_2_joint
      - /ur10_1/wrist_3_joint
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      /ur10_1/robotiq_85_left_knuckle_joint